{{- if not .Values.proxmox.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaos-sloth.fullname" . }}
  labels:
    {{- include "chaos-sloth.labels" . | nindent 4 }}
type: Opaque
stringData:
  token-secret: {{ .Values.proxmox.tokenSecret | quote }}
{{- end }}
