{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaos-sloth.serviceAccountName" . }}
  labels:
    {{- include "chaos-sloth.labels" . | nindent 4 }}
{{- end }}
